#!/bin/bash
set -xe
platform=$HOSTTYPE
if [ "$HOSTTYPE" == "powerpc64le" ]; then
  platform=ppc64le
fi
os="ubuntu-15.04"
base_dir="bigtop-base"/$os-$platform
master_dir="bigtop-hadoop-master"/$os-$platform
node_dir="bigtop-hadoop-node"/$os-$platform
worker_dir="bigtop-hadoop-worker"/$os-$platform
spark_dir="bigtop-spark-master"/$os-$platform
zeppelin_dir="bigtop-zeppelin"/$os-$platform
hive_dir="bigtop-hive"/$os-$platform

if [[ ! -d $base_dir ]]; then
   echo "ERROR : not supported platform"
   exit 1
fi 
OPS="--rm --no-cache"
cd $base_dir
docker build -t bigtop-base:$os-$platform .
cd ../..

cd $node_dir
cp ../../common/*.sh .
docker build --rm --no-cache -t bigtop-hadoop-node:$os-$platform .
rm *.sh
cd ../..

cd $master_dir
docker build $OPS -t bigtop-hadoop-master:$os-$platform .
cd ../..

cd $worker_dir
docker build $OPS -t bigtop-hadoop-worker:$os-$platform .
cd ../..

cd $spark_dir
docker build $OPS -t bigtop-spark-master:$os-$platform .
cd ../..

cd $zeppelin_dir
docker build $OPS -t bigtop-zeppelin:$os-$platform .
cd ../..

cd $hive_dir
docker build $OPS -t bigtop-hive:$os-$platform .
cd ../..

