#!/bin/bash
set -xe
platform=$HOSTTYPE
if [[ $HOSTTYPE=="powerpc64" ]]; then
  platform=ppc64le
fi
os="ubuntu-15.04"
base_dir="bigtop-base"/$os-$platform
master_dir="bigtop-hadoop-master"/$os-$platform
worker_dir="bigtop-hadoop-node"/$os-$platform
if [[ ! -d $base_dir ]]; then
   echo "ERROR : not supported platform"
   exit 1
fi 
cd $base_dir
docker build --rm --no-cache -t bigtop-base:$os-$platform .
cd ../..

cd $worker_dir
cp ../../common/*.sh .
docker build --rm --no-cache -t bigtop-hadoop-node:$os-$platform .
rm *.sh
cd ../..

cd $master_dir
docker build --rm --no-cache -t bigtop-hadoop-master:$os-$platform .
cd ../..



